// Requests
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';

// In case successfully

export const DELETE_PRODUCT = 'DELETE_PRODUCT_REQUEST';
export const EDIT_PRODUCT = 'EDIT_PRODUCT_REQUEST';
export const CREATE_PRODUCT = 'CREATE_PRODUCT_REQUEST';
